// Generated by LiveScript 1.4.0
(function(){
  describe('calc', function(){
    var services;
    beforeEach(module('ablsdk'));
    services = {
      ablcalc: {}
    };
    beforeEach(inject(function(_ablcalc_){
      var ablcalc;
      return ablcalc = _ablcalc_;
    }));
    return console.log(services.ablcalc);
  });
}).call(this);
