// Generated by LiveScript 1.4.0
(function(){
  describe('calc', function(){
    beforeEach(module('ablsdk'));
    return beforeEach(inject(function(ablslot){
      return console.log(1);
    }));
  });
}).call(this);
