// Generated by LiveScript 1.4.0
(function(){
  describe('calc', function(){
    beforeEach(module('ablsdk'));
    return describe('Constructor', function(it){
      return it('assigns a name', function(){
        return expect(new Person('Ben')).to.have.property('name', 'Ben');
      });
    });
  });
}).call(this);
