// Generated by LiveScript 1.4.0
(function(){
  angular.module('ablsdk').service('loader', function($xabl){
    return {
      load: function(callback){
        var config;
        config = $.param({
          location: state.location,
          pageSize: 100,
          page: state.page,
          noEmpty: false,
          dateRange: [moment().startOf('day').format(), moment().clone().add(12, 'months').endOf('day').format()]
        });
        return $xabl.get("operators/" + $xabl.options.key).error(function(){
          throw "An error occurred getting Operator information for key " + $xabl.options.key;
        }).success(function(info){
          return $xabl.get("activities?" + config).success(function(resp){
            return callback({
              activities: resp.list,
              preferences: resp.preferences,
              info: info
            });
          });
        });
      }
    };
  });
}).call(this);
