// Generated by LiveScript 1.3.1
angular.module('ablsdk', []);
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('ablbook', function($xabl, p, stripe, debug, prefill, ablcalc){
  return function(activity, globalCallback){
    var state, getDay, investigateDate, valid, error, closeError, typing, resetIdenpotencyKey, few, sum, disabledOrder, cardify, expDateChanged, cardChanged, stripeProcess, paymentSetup, checkout, agree, isError, showError, fields, tryCheckout, message, placeholder, x$;
    state = {
      triedCheckout: false,
      typing: '',
      braintreeClient: null,
      loading: false,
      idenpotencyKey: null,
      form: {
        error: "",
        agreed: false,
        email: '',
        name: '',
        phone: '',
        address: '',
        location: {},
        notes: '',
        date: {
          start: null,
          end: null
        },
        creditCard: {
          card: '',
          expDate: '',
          cvv: ''
        }
      },
      calendar: {
        value: null,
        visible: false,
        currentActivity: activity,
        closed: function(chosen){
          state.form.date.start = state.calendar.date.start;
          state.form.date.end = state.calendar.date.end;
          return globalCallback('slot-chosen', chosen);
        }
      }
    };
    getDay = function(date){
      var res;
      if (date != null) {
        res = (date != null ? date.format : void 8) != null
          ? date
          : moment(date);
        return parseInt(
        res.format('YYYYMMDD'));
      } else {
        return null;
      }
    };
    investigateDate = function(bag){
      var _;
      return _ = (function(){
        switch (false) {
        case bag.start !== null:
          return 'none';
        case getDay(bag.start) === getDay(bag.end):
          return 'different';
        default:
          return 'same';
        }
      }());
    };
    valid = function(form){
      return !state.loading && form.$valid;
    };
    error = function(message){
      return state.form.error = message;
    };
    closeError = function(){
      return error("");
    };
    typing = function(name){
      state.triedCheckout = false;
      return state.typing = name;
    };
    resetIdenpotencyKey = function(){
      var s;
      return state.idenpotencyKey = (s = function(){
        return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
      }, s() + s() + '-' + s() + '-' + s() + '-' + s() + '-' + s() + s() + s());
    };
    resetIdenpotencyKey();
    few = function(arr){
      var ref$;
      return (ref$ = arr != null ? typeof arr.filter == 'function' ? arr.filter(function(it){
        return it.quantity > 0;
      }) : void 8 : void 8) != null
        ? ref$
        : [];
    };
    sum = function(arr){
      switch (false) {
      case typeof arr !== 'undefined':
        return 0;
      case typeof arr !== null:
        return 0;
      case arr.length !== 0:
        return 0;
      default:
        return arr.reduce(function(x, y){
          return x + y;
        });
      }
    };
    disabledOrder = function(){
      return sum(state.calendar.calc.attendees.map(function(it){
        return it.quantity;
      })) === 0;
    };
    cardify = function(val, val2){
      var newval;
      newval = (function(){
        switch (false) {
        case val.length !== 4:
          return val + " ";
        case val.length !== 9:
          return val + " ";
        case val.length !== 14:
          return val + " ";
        case val.length !== 19:
          return val + " ";
        default:
          return val;
        }
      }());
      return newval + val2;
    };
    expDateChanged = function(){
      var value, e, ref$, t;
      value = event.target.value;
      e = (ref$ = value != null ? value.replace('/', '') : void 8) != null ? ref$ : "";
      t = function(it){
        return it != null ? it : "";
      };
      return state.form.creditCard.expDate = (function(){
        switch (false) {
        case !(e.length > 2):
          return e[0] + e[1] + '/' + t(e[2]) + t(e[3]);
        default:
          return e;
        }
      }());
    };
    cardChanged = function(event){
      var value;
      value = event.target.value;
      if (typeof value === 'undefined') {
        return;
      }
      return state.form.creditCard.card = function(it){
        return it.substr(0, 19);
      }(
      p.fold(cardify, "")(
      function(it){
        return it.split(' ').join('');
      }(
      value)));
    };
    stripeProcess = function(key, callback){
      var cc, expDate, f, req;
      if (typeof key === 'undefined') {
        state.loading = false;
        return error("Stripe key is not defined");
      }
      stripe.setPublishableKey(key);
      cc = state.form.creditCard;
      expDate = cc.expDate.split('/');
      f = state.form;
      req = {
        number: cc.card,
        cvc: cc.cvv,
        exp_month: expDate[0],
        exp_year: "20" + expDate[1],
        fullName: f.name,
        location: f.location,
        state: f.state
      };
      return stripe.createToken(req, function(err, token){
        var a, eventId, req;
        if (err != null) {
          state.loading = false;
          return error(err);
        }
        a = activity;
        eventId = a.timeslots.filter(function(it){
          return it._id === state.calendar._id;
        })[0].eventId;
        req = {
          stripeToken: token,
          couponId: state.calendar.calc.coupon.codes.length > 0 ? state.calendar.calc.coupon.codes[0].couponId : undefined,
          paymentMethod: 'credit',
          eventInstanceId: eventId + '_' + state.calendar.date.origin,
          addons: p.pairsToObj(
          p.map(function(a){
            return [a._id, a.quantity];
          })(
          state.calendar.calc.addons)),
          attendees: p.pairsToObj(
          p.map(function(a){
            return [a.name, a.quantity];
          })(
          state.calendar.calc.attendees)),
          answers: p.pairsToObj(
          p.map(function(a){
            return [a._id, a.answer];
          })(
          state.calendar.questions)),
          fullName: f.name,
          email: f.email,
          phoneNumber: f.phone,
          notes: f.notes,
          location: f.location,
          currency: 'usd',
          _customHeaders: {
            "Idempotency-Key": state.idenpotencyKey
          }
        };
        return $xabl.post('bookings', req).success(function(data){
          if (data.bookingId != null) {
            resetIdenpotencyKey();
            return callback();
          } else {
            return error(data.error);
          }
        }).error(function(e){
          var ref$, ref1$;
          return error((ref$ = (ref1$ = e.errors) != null ? ref1$[0] : void 8) != null ? ref$ : "Server error");
        })['finally'](function(){
          return state.loading = false;
        });
      });
    };
    paymentSetup = function(){
      return $xabl.get('payments/setup');
    };
    checkout = function(form){
      if (state.loading === true) {
        return;
      }
      state.triedCheckout = true;
      if (valid(form)) {
        state.loading = true;
        return paymentSetup().success(function(data){
          return stripeProcess(data.publicKey, function(){
            return globalCallback('success', data);
          });
        }).error(function(err){
          state.loading = false;
          error(err);
          return globalCallback('error', error);
        });
      } else {
        return error("Please correct the form");
      }
    };
    agree = function(){
      state.form.agreed = !state.form.agreed;
      return tryCheckout();
    };
    isError = function(v){
      return v.required || v.pattern || v.minlength || v.maxlength || v.phone;
    };
    showError = function(name, v){
      switch (false) {
      case !v.required:
        return name + " is required";
      case !v.pattern:
        return "Please follow the example " + fields[name].example;
      case !v.minlength:
        return name + " is too short";
      case !v.maxlength:
        return name + " is too long";
      case !v.phone:
        return name + " is not valid phone number";
      default:
        return "please check " + name;
      }
    };
    fields = {
      email: {
        pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
        example: 'nickname@email.com',
        placeholder: 'Email'
      },
      name: {
        pattern: '',
        example: 'Your name',
        placeholder: 'Name'
      },
      phone: {
        pattern: /^[0-9]{3}[-][0-9]{3}[-][0-9]{3,5}$/i,
        placeholder: "Phone +1 123-456-1234",
        example: "+1 123-456-1234"
      },
      address: {
        pattern: '',
        example: 'Address',
        placeholder: 'Home address'
      },
      notes: {
        pattern: '',
        example: "Notes",
        placeholder: "Notes"
      },
      card: {
        pattern: /[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}/i,
        example: '0000 0000 0000 0000',
        placeholder: "Card #"
      },
      expDate: {
        pattern: /[0-9]{2}\/[0-9]{2}/i,
        example: "05/15",
        placeholder: 'Exp date'
      },
      startDate: {},
      cvv: {
        pattern: /[0-9]{3,4}/i,
        example: "000",
        placeholder: "CVV"
      }
    };
    tryCheckout = function(){
      if (state.form.agreed) {
        return state.triedCheckout = true;
      }
    };
    message = function(form, name){
      var field, val, ref$, ref1$, ref2$, ref3$, ref4$;
      if (state.triedCheckout === true) {
        for (field in fields) {
          if (fields.hasOwnProperty(field)) {
            val = (ref$ = form[field]) != null ? ref$.$error : void 8;
            if (val && isError(val)) {
              if (field === name) {
                return showError(field, val);
              }
              return "";
            }
          }
        }
        return "";
      } else {
        for (field in fields) {
          if (fields.hasOwnProperty(field)) {
            val = (ref1$ = form[field]) != null ? ref1$.$error : void 8;
            if (val && isError(val) && val.maxlength) {
              if (field === name) {
                return showError(field, val);
              }
              return "";
            }
          }
        }
        if (state.typing === name) {
          if (((ref2$ = form[name]) != null ? (ref3$ = ref2$.$error) != null ? ref3$.pattern : void 8 : void 8) != null && ((ref4$ = fields[name].example) != null ? ref4$.length : void 8) > 0) {
            return "example: " + fields[name].example;
          }
        }
      }
    };
    placeholder = function(name){
      if (state.typing === name) {
        return fields[name].example;
      } else {
        return fields[name].placeholder;
      }
    };
    prefill(function(){
      var f, c;
      f = state.form;
      f.email = "test@debug.com";
      f.name = "Test User";
      f.phone = "+380665243646";
      f.address = "664 Cypress Lane, Campbell, CA, United States";
      f.notes = "Some test notes";
      c = state.form.creditCard;
      c.card = "5105 1051 0510 5100";
      c.expDate = "05/17";
      c.cvv = "333";
      return state.form.agreed = true;
    });
    x$ = state;
    x$.investigateDate = investigateDate;
    x$.placeholder = placeholder;
    x$.closeError = closeError;
    x$.checkout = checkout;
    x$.agree = agree;
    x$.fields = fields;
    x$.few = few;
    x$.expDateChanged = expDateChanged;
    x$.cardChanged = cardChanged;
    x$.disabledOrder = disabledOrder;
    x$.typing = typing;
    x$.message = message;
    return state;
  };
});
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('ablcalc', function($xabl, $timeout){
  var sum;
  sum = function(arr){
    switch (false) {
    case typeof arr !== 'undefined':
      return 0;
    case typeof arr !== null:
      return 0;
    case arr.length !== 0:
      return 0;
    default:
      return arr.reduce(function(x, y){
        return x + y;
      });
    }
  };
  return function(inputCharges){
    var charges, makeEditable, byPrice, state, calcSubtotal, calcTaxFee, calcTaxesFees, showPrice, calcPrice, showAddonPrice, calcAddonPrice, totalAddons, calcCoupon, calcTotal, coupon;
    charges = inputCharges != null ? inputCharges.filter(function(it){
      return it.status === 'active';
    }) : void 8;
    makeEditable = function(charge){
      var ref$;
      return {
        name: charge.name,
        quantity: (ref$ = charge.count) != null ? ref$ : 0,
        amount: charge.amount,
        _id: charge._id
      };
    };
    byPrice = function(a, b){
      return b.amount - a.amount;
    };
    state = {
      attendees: charges != null ? charges.filter(function(it){
        return it.type === 'aap';
      }).map(makeEditable).sort(byPrice) : void 8,
      addons: charges != null ? charges.filter(function(it){
        return it.type === 'addon';
      }).map(makeEditable) : void 8
    };
    calcSubtotal = function(){
      return sum(
      state.attendees.map(calcPrice)) + totalAddons();
    };
    calcTaxFee = function(charge){
      switch (false) {
      case charge.type !== 'tax':
        return calcSubtotal() / 100 * charge.amount;
      case charge.type !== 'fee':
        return sum(
        state.attendees.map(function(it){
          return it.quantity;
        })) * charge.amount;
      default:
        return 0;
      }
    };
    calcTaxesFees = function(){
      return sum(
      charges.map(calcTaxFee));
    };
    showPrice = function(attendee){
      var ref$, ref1$, ref2$;
      return (ref$ = (ref1$ = charges.filter(function(it){
        return it.type === 'aap' && it.name === attendee.name;
      })) != null ? (ref2$ = ref1$[0]) != null ? ref2$.amount : void 8 : void 8) != null ? ref$ : 0;
    };
    calcPrice = function(attendee){
      return showPrice(attendee) * attendee.quantity;
    };
    showAddonPrice = function(addon){
      return sum(
      state.addons.filter(function(it){
        return it.name === addon.name;
      }).map(function(it){
        return it.amount;
      }));
    };
    calcAddonPrice = function(addon){
      return showAddonPrice(addon) * addon.quantity;
    };
    totalAddons = function(){
      return sum(
      state.addons.map(calcAddonPrice));
    };
    calcCoupon = function(){
      var subtotal, amountOff, _;
      subtotal = calcSubtotal();
      amountOff = function(){
        switch (false) {
        case !(coupon.codes[0].amountOff < subtotal):
          return coupon.codes[0].amountOff;
        default:
          return subtotal;
        }
      };
      _ = (function(){
        switch (false) {
        case coupon.codes.length !== 0:
          return 0;
        case coupon.codes[0].amountOff == null:
          return amountOff();
        case coupon.codes[0].percentOff == null:
          return subtotal / 100 * coupon.codes[0].percentOff;
        default:
          return 0;
        }
      }());
      return _;
    };
    calcTotal = function(){
      return calcSubtotal() + calcTaxesFees() - calcCoupon();
    };
    coupon = {
      codes: [],
      calc: calcCoupon,
      remove: function(c){
        var index;
        index = coupon.codes.indexOf(c);
        if (index > -1) {
          return coupon.codes.splice(index, 1);
        }
      },
      add: function(activity){
        var ref$, apply;
        if (((ref$ = coupon.code) != null ? ref$ : "").length === 0) {
          return;
        }
        coupon.code = coupon.code.toUpperCase();
        coupon.error = (function(){
          switch (false) {
          case coupon.code.length !== 0:
            return "Code is required";
          case !(coupon.code.length < 6):
            return "6 chars are required";
          default:
            return "";
          }
        }());
        if (coupon.error.length > 0) {
          return;
        }
        apply = function(data){
          var success;
          success = function(){
            coupon.codes.push(data);
            coupon.code = "";
            coupon.success = "Coupon " + data.couponId + " added successfully";
            $timeout(function(){
              var ref$;
              return ref$ = coupon.success, delete coupon.success, ref$;
            }, 3000);
            return "";
          };
          return coupon.error = (function(){
            switch (false) {
            case !(data.maxRedemptions !== 0 && data.maxRedemptions <= data.redemptions):
              return "This coupon has been fully redeemed.";
            case !(moment().diff(moment(data.redeemBy), 'minutes') > 0):
              return "This coupon is expired";
            case !(data.activities.length > 0 && data.activities[0] !== activity):
              return "This coupon is not valid for this activity.";
            default:
              return success();
            }
          }());
        };
        return $xabl.get("coupon/" + coupon.code).success(function(data){
          return apply(data);
        }).error(function(data){
          var ref$, ref1$;
          return coupon.error = (ref$ = data != null ? (ref1$ = data.errors) != null ? ref1$[0] : void 8 : void 8) != null ? ref$ : "Coupon not found";
        });
      },
      code: ""
    };
    return {
      coupon: coupon,
      addons: state.addons,
      attendees: state.attendees,
      totalWithoutTaxesfees: calcSubtotal,
      calcCoupon: calcCoupon,
      calcTaxFee: calcTaxFee,
      calcTaxesFees: calcTaxesFees,
      showPrice: showPrice,
      calcPrice: calcPrice,
      showAddonPrice: showAddonPrice,
      calcAddonPrice: calcAddonPrice,
      totalAddons: totalAddons,
      calcSubtotal: calcSubtotal,
      calcTotal: calcTotal
    };
  };
});
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('ablapi', function($xabl){
  return {
    timeslots: function(options){
      var req;
      req = $.param({
        activity: options.activityId,
        "status[event]": 'all',
        dateRange: [moment(options.startTime).clone().startOf('day').startOf('month').toISOString(), moment(options.endTime).clone().startOf('day').endOf('month').endOf('day').toISOString()]
      });
      return $xabl.get("timeslots?" + req);
    }
  };
});
// Generated by LiveScript 1.3.1
var toString$ = {}.toString;
angular.module('ablsdk').service('crud', function($xabl, $rootScope, debug, $mdDialog, safeApply, watcher, p){
  return function(url, initOptions){
    var parsedUrl, state, factory, provider, ref$, configureUrl, $scope, i, removeFromMemory, save, update, add, success, fetch, splice, remove, watchers, improve;
    parsedUrl = url.split('@');
    url = parsedUrl[0];
    state = {
      loading: false
    };
    factory = {
      localStorage: {
        remove: function(item){},
        add: function(item){},
        update: function(item){},
        fetch: function(item){}
      },
      memory: {
        remove: function(item){
          return removeFromMemory(item);
        },
        add: function(item, callback){
          Array.prototype.push.call(i, item);
          return typeof callback == 'function' ? callback(item) : void 8;
        },
        update: function(item, callback){
          return typeof callback == 'function' ? callback(item) : void 8;
        },
        fetch: function(){
          return state.loading = false;
        }
      },
      backend: {
        remove: function(item){
          return $xabl['delete'](url + "/" + item._id).success(function(){
            return removeFromMemory(item);
          });
        },
        update: function(item, callback){
          return $xabl.update(url + "/" + item._id, item).success(function(data){
            state.loading = false;
            return typeof callback == 'function' ? callback(data) : void 8;
          });
        },
        add: function(item, callback){
          return $xabl.create(url, item).success(function(data){
            debug('backend-success', data);
            success(data);
            return typeof callback == 'function' ? callback(data) : void 8;
          });
        },
        fetch: function(){
          var options;
          debug('fetch', configureUrl(url), i.options);
          options = angular.copy(i.options);
          delete options.$url;
          return $xabl.get(configureUrl(url), {
            params: options
          }).success(function(data, status, headers){
            var params, r;
            i.length = 0;
            params = function(name){
              var header, parser;
              header = headers()[name];
              if (header != null) {
                parser = document.createElement('a');
                parser.href = headers()[name];
                return JSON.parse('{"' + decodeURI(parser.search.substr(1, 2000)).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g, '":"') + '"}');
              } else {
                return undefined;
              }
            };
            i.options.total = (r = params('x-last-page-url'), r != null
              ? parseInt(r.page) * parseInt(r.pageSize)
              : data.length);
            i.options.pageSize = (r = params('x-first-page-url'), r != null
              ? parseInt(r.pageSize)
              : data.length);
            state.loading = false;
            return success(data);
          });
        }
      }
    };
    provider = factory[(ref$ = parsedUrl[1]) != null ? ref$ : 'backend'];
    configureUrl = function(url){
      var state, replace, u;
      state = {
        url: url
      };
      replace = function(pair){
        return state.url = state.url.replace(':' + pair[0], pair[1]);
      };
      u = i.getOptions().$url;
      if (u != null) {
        p.each(replace)(
        p.objToPairs(
        u));
      }
      return state.url;
    };
    $scope = $rootScope.$new();
    $scope.items = [];
    i = $scope.items;
    state.loading = false;
    removeFromMemory = function(item){
      var index;
      index = i.indexOf(item);
      if (index > -1) {
        return Array.prototype.splice.call(i, index, 1);
      }
    };
    save = function(item, callback){
      if (item._id != null) {
        return update(item, callback);
      } else {
        return add(item, callback);
      }
    };
    update = function(item, callback){
      if (state.loading) {
        return;
      }
      return provider.update(item, callback);
    };
    add = function(item, callback){
      if (state.loading) {
        return;
      }
      return provider.add(item, callback);
    };
    success = function(data){
      var parts, part, array;
      parts = url.split('/');
      part = parts[parts.length - 1];
      array = (function(){
        switch (false) {
        case toString$.call(data).slice(8, -1) !== 'Array':
          return data;
        case toString$.call(data[part]).slice(8, -1) !== 'Array':
          return data[part];
        case toString$.call(data).slice(8, -1) !== 'Object':
          return [data];
        default:
          return [];
        }
      }());
      Array.prototype.push.apply(i, array);
      return state.loading = false;
    };
    i.options = {};
    i.getOptions = function(){
      return i.options;
    };
    fetch = function(options){
      if (state.loading) {
        return;
      }
      switch (toString$.call(options).slice(8, -1)) {
      case 'Function':
        i.getOptions = options;
        return fetch({});
      case 'Number':
        i.options.page = options;
        break;
      case 'Object':
        i.options = angular.extend({}, i.getOptions(), options);
      }
      state.loading = true;
      if (i.options.page != null) {
        if (i.options.page === 1) {
          delete i.options.page;
        } else {
          i.options.page -= 1;
        }
      }
      return provider.fetch();
    };
    fetch(initOptions);
    splice = function(){
      var removed;
      if (state.loading) {
        return;
      }
      removed = Array.prototype.splice.apply(i, arguments);
      return removed.forEach(provider.remove);
    };
    remove = function(item, $event, options){
      var defaultOptions, ref$;
      if (state.loading) {
        return;
      }
      defaultOptions = {
        title: "Confirm Delete",
        content: "Are you sure you want to delete this item?",
        ok: "Confirm",
        cancel: "Cancel"
      };
      return $mdDialog.show($mdDialog.confirm().title((ref$ = options != null ? options.title : void 8) != null
        ? ref$
        : defaultOptions.title).content((ref$ = options != null ? options.content : void 8) != null
        ? ref$
        : defaultOptions.content).ok((ref$ = options != null ? options.ok : void 8) != null
        ? ref$
        : defaultOptions.ok).cancel((ref$ = options != null ? options.cancel : void 8) != null
        ? ref$
        : defaultOptions.cancel).targetEvent($event)).then(function(){
        return provider.remove(item);
      }, function(){});
    };
    watchers = [];
    improve = function(source){
      var observers, bind;
      observers = [];
      bind = curry$(function(name, func){
        var bound, mutate;
        bound = [];
        improve(bound);
        mutate = function(){
          var mutated;
          mutated = Array.prototype[name].call(source, func);
          bound.length = 0;
          return Array.prototype.push.apply(bound, mutated);
        };
        observers.push(mutate);
        mutate();
        return bound;
      });
      source.loading = function(){
        return state.loading;
      };
      source.toArray = function(){
        var a;
        a = [];
        Array.prototype.push.apply(a, source);
        return a;
      };
      source.fetchOn = function(array, $scope){
        $scope.$watch(array, bind$(i, 'fetch'), true);
        return source;
      };
      source.watch = function(array, $scope){
        var func;
        func = function(){
          return safeApply(function(){
            return observers.forEach(function(it){
              return it();
            });
          });
        };
        if ($scope != null) {
          watchers.push({
            array: $scope[array],
            func: func
          });
          $scope.$watch(array, func, true);
        } else {
          watchers.push({
            array: array,
            func: func
          });
          watcher.watch(array, func);
        }
        return source;
      };
      source.watch(source);
      ['map', 'filter'].forEach(function(item){
        return source[item] = bind(item);
      });
      source.push = add;
      source.save = save;
      source.fetch = fetch;
      source.remove = remove;
      source.splice = splice;
      return source.toArray = function(){
        return angular.copy(source);
      };
    };
    i.listen = function($scope){
      $scope.$on('$destroy', function(){
        var i$, ref$, len$, item, results$ = [];
        for (i$ = 0, len$ = (ref$ = watchers).length; i$ < len$; ++i$) {
          item = ref$[i$];
          results$.push(watcher.unwatch(item.array, item.func));
        }
        return results$;
      });
      return i;
    };
    improve(i);
    return i;
  };
});
function curry$(f, bound){
  var context,
  _curry = function(args) {
    return f.length > 1 ? function(){
      var params = args ? args.concat() : [];
      context = bound ? context || this : this;
      return params.push.apply(params, arguments) <
          f.length && arguments.length ?
        _curry.call(context, params) : f.apply(context, params);
    } : f;
  };
  return _curry();
}
function bind$(obj, key, target){
  return function(){ return (target || obj)[key].apply(obj, arguments) };
}
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('browser', function($window){
  var name;
  name = function(){
    var userAgent, browsers, key;
    userAgent = $window.navigator.userAgent;
    browsers = {
      chrome: /chrome/i,
      safari: /safari/i,
      firefox: /firefox/i,
      ie: /msie/i
    };
    for (key in browsers) {
      if (browsers[key].test($window.navigator.userAgent)) {
        return key;
      }
    }
    return 'unknown';
  };
  return {
    name: name()
  };
});
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('abldate', function(debug){
  return function(timeZone){
    var hack, dst;
    hack = function(input, tz){
      var d, z;
      d = bind$(moment(input), 'format');
      z = bind$(tz, 'format');
      return moment(d('YYYY-MM-DD HH:mm ') + z('Z'), "YYYY-MM-DD HH:mm Z");
    };
    dst = function(d, date){
      return d.add(moment(date).tz(timeZone).utcOffset() - d.utcOffset(), 'minute');
    };
    return {
      backendify: function(date){
        var d;
        d = hack(date, moment().tz(timeZone)).tz(timeZone);
        debug('timezone', timeZone);
        dst(d);
        return d.tz("UTC").format("YYYY-MM-DD\\THH:mm:ss\\Z");
      },
      frontendify: function(date){
        var d;
        d = moment(date).tz(timeZone);
        debug('timezone', timeZone);
        dst(d, d);
        return hack(d, moment(date)).toDate();
      }
    };
  };
});
function bind$(obj, key, target){
  return function(){ return (target || obj)[key].apply(obj, arguments) };
}
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('formula', function(p, debug){
  var getSlotPrice, getVisualPrice;
  getSlotPrice = function(type, slot){
    var arr, ref$;
    arr = (ref$ = slot != null ? slot.charges : void 8) != null
      ? ref$
      : [];
    return function(it){
      var ref$;
      return (ref$ = it != null ? it.amount : void 8) != null ? ref$ : 0;
    }(
    p.find(function(it){
      return it.type === type || it.subtype === type || it.description === type;
    })(
    arr));
  };
  getVisualPrice = function(ac){
    var ref$, merge, onlyAdult, all, mergedAdults, mergedAll, max, final;
    if ((ac != null ? (ref$ = ac.timeslots) != null ? ref$.length : void 8 : void 8) > 0) {
      merge = function(arrays){
        return [].concat.apply([], arrays);
      };
      onlyAdult = function(slot){
        var type, ref$;
        type = 'Adult';
        return p.map(function(it){
          return it.amount;
        })(
        p.filter(function(it){
          return it.status === 'active';
        })(
        p.filter(function(it){
          return it.type === type || it.subtype === type || it.description === type;
        })(
        (ref$ = slot != null ? slot.charges : void 8) != null
          ? ref$
          : [])));
      };
      all = function(slot){
        var ref$;
        return p.map(function(it){
          return it.amount;
        })(
        (ref$ = slot != null ? slot.charges : void 8) != null
          ? ref$
          : []);
      };
      mergedAdults = merge(ac.timeslots.map(onlyAdult));
      mergedAll = merge(ac.timeslots.map(all));
      max = function(array){
        return Math.max.apply(Math, array);
      };
      final = (function(){
        switch (false) {
        case !(mergedAdults.length > 0):
          return max(mergedAdults);
        case !(mergedAll.length > 0):
          return max(mergedAll);
        default:
          return 0;
        }
      }());
      return final;
    } else {
      return 'Non';
    }
  };
  return {
    getSlotPrice: function(slot){
      return getSlotPrice('Adult', slot);
    },
    getVisualPrice: getVisualPrice,
    getAdultPrice: function(ac){
      var ref$;
      return getSlotPrice('Adult', ac != null ? (ref$ = ac.timeslots) != null ? ref$[0] : void 8 : void 8);
    },
    getYouthPrice: function(ac){
      var ref$;
      return getSlotPrice('Youth', ac != null ? (ref$ = ac.timeslots) != null ? ref$[0] : void 8 : void 8);
    }
  };
});
// Generated by LiveScript 1.3.1
var toString$ = {}.toString;
angular.module('ablsdk').factory('debug', function(enabledDebug){
  return function(input){
    var ref$;
    if (enabledDebug) {
      switch (toString$.call(input).slice(8, -1)) {
      case 'Function':
        return input();
      default:
        return typeof console != 'undefined' && console !== null ? (ref$ = console.log) != null ? ref$.apply(console, arguments) : void 8 : void 8;
      }
    }
  };
});
// Generated by LiveScript 1.3.1
angular.module('ablsdk').service('p', function(){
  var first;
  return {
    head: first = function(xs){
      return xs[0];
    },
    each: curry$(function(f, xs){
      var i$, len$, x;
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        f(x);
      }
      return xs;
    }),
    map: curry$(function(f, xs){
      var i$, len$, x, results$ = [];
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        results$.push(f(x));
      }
      return results$;
    }),
    fold: curry$(function(f, memo, xs){
      var i$, len$, x;
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        memo = f(memo, x);
      }
      return memo;
    }),
    filter: curry$(function(f, xs){
      var i$, len$, x, results$ = [];
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        if (f(x)) {
          results$.push(x);
        }
      }
      return results$;
    }),
    find: curry$(function(f, xs){
      var i$, len$, x;
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        if (f(x)) {
          return x;
        }
      }
    }),
    pairsToObj: function(object){
      var i$, len$, x, resultObj$ = {};
      for (i$ = 0, len$ = object.length; i$ < len$; ++i$) {
        x = object[i$];
        resultObj$[x[0]] = x[1];
      }
      return resultObj$;
    },
    objToPairs: function(object){
      var key, value, results$ = [];
      for (key in object) {
        value = object[key];
        results$.push([key, value]);
      }
      return results$;
    },
    values: function(object){
      var key, value, results$ = [];
      for (key in object) {
        value = object[key];
        results$.push(value);
      }
      return results$;
    },
    any: curry$(function(f, xs){
      var i$, len$, x;
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        if (f(x)) {
          return true;
        }
      }
      return false;
    }),
    notAny: curry$(function(f, xs){
      var i$, len$, x;
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        if (f(x)) {
          return false;
        }
      }
      return true;
    }),
    sum: function(xs){
      var result, i$, len$, x;
      result = 0;
      for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
        x = xs[i$];
        result += x;
      }
      return result;
    },
    sort: function(xs){
      return xs.concat().sort(function(x, y){
        if (x > y) {
          return 1;
        } else if (x < y) {
          return -1;
        } else {
          return 0;
        }
      });
    },
    sortWith: curry$(function(f, xs){
      return xs.concat().sort(f);
    }),
    sortBy: curry$(function(f, xs){
      return xs.concat().sort(function(x, y){
        if (f(x) > f(y)) {
          return 1;
        } else if (f(x) < f(y)) {
          return -1;
        } else {
          return 0;
        }
      });
    }),
    reverse: function(xs){
      return xs.concat().reverse();
    }
  };
});
function curry$(f, bound){
  var context,
  _curry = function(args) {
    return f.length > 1 ? function(){
      var params = args ? args.concat() : [];
      context = bound ? context || this : this;
      return params.push.apply(params, arguments) <
          f.length && arguments.length ?
        _curry.call(context, params) : f.apply(context, params);
    } : f;
  };
  return _curry();
}
// Generated by LiveScript 1.3.1
angular.module('ablsdk').filter('mdate', function(debug){
  return function(obj, mask){
    if (obj != null) {
      return obj.format(mask);
    } else {
      return null;
    }
  };
});
