// Generated by LiveScript 1.4.0
angular.module('ablsdk', []);
// Generated by LiveScript 1.4.0
angular.module('ablsdk').service('ablapi', function($xabl){
  return {
    timeslots: function(options){
      var req;
      req = $.param({
        activity: options.activityId,
        "status[event]": 'all',
        dateRange: [moment(options.startTime).clone().startOf('day').startOf('month').toISOString(), moment(options.endTime).clone().startOf('day').endOf('month').endOf('day').toISOString()]
      });
      return $xabl.get("timeslots?" + req);
    }
  };
});
// Generated by LiveScript 1.4.0
angular.module('ablsdk').service('ablbook', function($xabl, p, stripe, debug, prefill, safeApply){
  return function(activity, globalCallback){
    var state, getDay, investigateDate, valid, issue, error, closeError, resetIdenpotencyKey, few, sum, disabledOrder, cardify, getEventInstanceId, stripeProcess, paymentSetup, validate, checkout, agree, isError, showErrorLogical, showError, fields, tryCheckout, message, placeholder, x$;
    state = {
      triedCheckout: false,
      typing: '',
      braintreeClient: null,
      loading: false,
      idenpotencyKey: null,
      form: {
        error: "",
        agreed: false,
        email: '',
        name: '',
        phone: '',
        address: '',
        location: {},
        notes: '',
        date: {
          start: null,
          end: null
        },
        creditCard: {
          card: '',
          expDate: '',
          cvv: '',
          address_zip: ''
        }
      },
      calendar: {
        value: null,
        visible: false,
        currentActivity: activity,
        closed: function(chosen){
          state.form.date.start = state.calendar.date.start;
          state.form.date.end = state.calendar.date.end;
          return globalCallback('slot-chosen', chosen);
        }
      }
    };
    getDay = function(date){
      var res;
      if (date != null) {
        res = (date != null ? date.format : void 8) != null
          ? date
          : moment(date);
        return parseInt(
        res.format('YYYYMMDD'));
      } else {
        return null;
      }
    };
    investigateDate = function(bag){
      var _;
      return _ = (function(){
        switch (false) {
        case bag.start !== null:
          return 'none';
        case getDay(bag.start) === getDay(bag.end):
          return 'different';
        default:
          return 'same';
        }
      }());
    };
    valid = function(form){
      return !state.loading && form.$valid;
    };
    issue = function(form){
      var field, text;
      for (field in fields) {
        if (fields.hasOwnProperty(field)) {
          text = message(form, field);
          if ((text != null ? text.length : void 8) > 0) {
            return text;
          }
        }
      }
      return "Please check the form";
    };
    error = function(message){
      return state.form.error = message;
    };
    closeError = function(){
      return error("");
    };
    resetIdenpotencyKey = function(){
      var s;
      return state.idenpotencyKey = (s = function(){
        return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
      }, s() + s() + '-' + s() + '-' + s() + '-' + s() + '-' + s() + s() + s());
    };
    resetIdenpotencyKey();
    few = function(arr){
      var ref$;
      return (ref$ = arr != null ? typeof arr.filter == 'function' ? arr.filter(function(it){
        return it.quantity > 0;
      }) : void 8 : void 8) != null
        ? ref$
        : [];
    };
    sum = function(arr){
      switch (false) {
      case typeof arr !== 'undefined':
        return 0;
      case typeof arr !== null:
        return 0;
      case arr.length !== 0:
        return 0;
      default:
        return arr.reduce(function(x, y){
          return x + y;
        });
      }
    };
    disabledOrder = function(){
      return sum(state.calendar.calc.attendees.map(function(it){
        return it.quantity;
      })) === 0;
    };
    cardify = function(val, val2){
      var newval;
      newval = (function(){
        switch (false) {
        case val.length !== 4:
          return val + " ";
        case val.length !== 9:
          return val + " ";
        case val.length !== 14:
          return val + " ";
        case val.length !== 19:
          return val + " ";
        default:
          return val;
        }
      }());
      return newval + val2;
    };
    getEventInstanceId = function(){
      var eventId;
      if (state.calendar._id == null) {
        throw "Cannot get event instance id because calendar._id is not defined";
      }
      eventId = function(it){
        return it != null ? it.eventId : void 8;
      }(
      p.find(function(it){
        return it._id === state.calendar._id;
      })(
      activity.timeslots));
      if (eventId == null) {
        throw "event id is not found by id " + state.calendar._id + " in [" + activity.timeslots.map(function(it){
          return it._id;
        }).join(',') + "]";
      }
      return eventId + '_' + state.calendar.date.origin;
    };
    stripeProcess = function(key, callback){
      var cc, expDate, f, req;
      if (typeof key === 'undefined') {
        state.loading = false;
        return error("Stripe key is not defined");
      }
      stripe.setPublishableKey(key);
      cc = state.form.creditCard;
      expDate = cc.expDate.split('/');
      f = state.form;
      req = {
        number: cc.card,
        cvc: cc.cvv,
        address_zip: cc.address_zip,
        exp_month: expDate[0],
        exp_year: "20" + expDate[1],
        fullName: f.name,
        location: f.location,
        state: f.state
      };
      return stripe.createToken(req, function(err, token){
        var a, makeNulls, req;
        if (err != null) {
          state.loading = false;
          return error(err);
        }
        a = activity;
        makeNulls = function(total){
          return p.map(function(){
            return null;
          })(
          (function(){
            var i$, to$, results$ = [];
            for (i$ = 1, to$ = total; i$ <= to$; ++i$) {
              results$.push(i$);
            }
            return results$;
          }()));
        };
        req = {
          stripeToken: token,
          couponId: state.calendar.calc.coupon.codes.length > 0 ? state.calendar.calc.coupon.codes[0].couponId : undefined,
          paymentMethod: 'credit',
          eventInstanceId: getEventInstanceId(),
          addons: p.pairsToObj(
          p.map(function(a){
            return [a._id, makeNulls(a.quantity)];
          })(
          state.calendar.calc.addons)),
          attendees: p.pairsToObj(
          p.map(function(a){
            return [a._id, makeNulls(a.quantity)];
          })(
          state.calendar.calc.attendees)),
          answers: p.pairsToObj(
          p.map(function(a){
            return [a._id, a.answer];
          })(
          state.calendar.questions)),
          adjustments: state.calendar.calc.adjustment.list,
          fullName: f.name,
          email: f.email,
          phoneNumber: f.phone,
          notes: f.notes,
          location: f.location,
          currency: 'usd',
          _customHeaders: {
            "Idempotency-Key": state.idenpotencyKey
          }
        };
        return $xabl.post('bookings', req).success(function(data){
          var ref$, ref1$;
          if (data.bookingId != null) {
            resetIdenpotencyKey();
            return callback(data);
          } else {
            return error((ref$ = (ref1$ = e.errors) != null ? ref1$[0] : void 8) != null ? ref$ : "Server error");
          }
        }).error(function(e){
          var ref$, ref1$;
          return error((ref$ = (ref1$ = e.errors) != null ? ref1$[0] : void 8) != null ? ref$ : "Server error");
        })['finally'](function(){
          return state.loading = false;
        });
      });
    };
    paymentSetup = function(){
      return $xabl.get('payments/setup');
    };
    validate = function(form){
      var isValid;
      if (state.loading === true) {
        return false;
      }
      state.triedCheckout = true;
      isValid = valid(form);
      if (!isValid) {
        error(issue(form));
      }
      return isValid;
    };
    checkout = function(form){
      if (validate(form)) {
        state.loading = true;
        return paymentSetup().success(function(data){
          return stripeProcess(data.publicKey, function(booking){
            state.booking = booking;
            return globalCallback('success', booking);
          });
        }).error(function(err){
          state.loading = false;
          error(err);
          return globalCallback('error', error);
        });
      }
    };
    agree = function(){
      state.form.agreed = !state.form.agreed;
      return tryCheckout();
    };
    isError = function(v){
      return v.required || v.pattern || v.minlength || v.maxlength || v.phone;
    };
    showErrorLogical = function(name, v){
      var s, show;
      s = fields[name].state;
      show = (function(){
        switch (false) {
        case !state.triedCheckout:
          return true;
        case !(!s.touched && !state.triedCheckout):
          return false;
        case !(s.active && !state.triedCheckout):
          return false;
        case !(!s.active && s.touched):
          return true;
        default:
          return false;
        }
      }());
      if (show) {
        return showError(name, v);
      } else {
        return "";
      }
    };
    showError = function(name, v){
      var ref$, ref1$, ref2$;
      switch (false) {
      case !v.required:
        return (ref$ = (ref1$ = fields[name]) != null ? (ref2$ = ref1$.message) != null ? ref2$.required : void 8 : void 8) != null
          ? ref$
          : name + " is required";
      case !v.pattern:
        return "Please follow the example " + fields[name].example;
      case !v.minlength:
        return name + " is too short";
      case !v.maxlength:
        return name + " is too long";
      case !v.phone:
        return name + " is not valid phone number";
      default:
        return "please check " + name;
      }
    };
    fields = {
      email: {
        pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
        example: 'nickname@email.com',
        placeholder: 'Email',
        state: {
          touched: false,
          active: false
        }
      },
      name: {
        pattern: '',
        example: 'Your name',
        placeholder: 'Name',
        state: {
          touched: false,
          active: false
        }
      },
      phone: {
        pattern: /^[0-9]{3}[-][0-9]{3}[-][0-9]{3,5}$/i,
        placeholder: "Phone +1 123-456-1234",
        example: "+1 123-456-1234",
        state: {
          touched: false,
          active: false
        }
      },
      address: {
        pattern: '',
        example: 'Address',
        placeholder: 'Home address',
        state: {
          touched: false,
          active: false
        }
      },
      notes: {
        pattern: '',
        example: "Notes",
        placeholder: "Notes",
        state: {
          touched: false,
          active: false
        }
      },
      address_zip: {
        pattern: '',
        example: '12345',
        placeholder: "Postal Code",
        normalize: function(value){
          return value;
        },
        state: {
          touched: false,
          active: false
        }
      },
      card: {
        pattern: /[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}/i,
        example: '0000 0000 0000 0000',
        placeholder: "Credit Card Number",
        normalize: function(value){
          if (typeof value === 'undefined') {
            return;
          }
          return state.form.creditCard.card = function(it){
            return it.substr(0, 19);
          }(
          p.fold(cardify, "")(
          function(it){
            return it.split(' ').join('');
          }(
          value)));
        },
        state: {
          touched: false,
          active: false
        }
      },
      expDate: {
        pattern: /[0-9]{2}\/[0-9]{2}/i,
        example: "05/15",
        placeholder: 'Exp Date (MM/YY)',
        normalize: function(value){
          var e, ref$, t;
          e = (ref$ = value != null ? value.replace('/', '') : void 8) != null ? ref$ : "";
          t = function(it){
            return it != null ? it : "";
          };
          return state.form.creditCard.expDate = (function(){
            switch (false) {
            case e.length !== 2:
              return e[0] + e[1] + '/';
            case !(e.length > 2):
              return e[0] + e[1] + '/' + t(e[2]) + t(e[3]);
            default:
              return e;
            }
          }());
        },
        state: {
          touched: false,
          active: false
        }
      },
      startDate: {},
      cvv: {
        pattern: /[0-9]{3,4}/i,
        example: "000",
        placeholder: "CVV",
        state: {
          touched: false,
          active: false
        }
      },
      agreed: {
        pattern: 'true',
        message: {
          required: "Please accept the terms and conditions"
        },
        state: {
          touched: false,
          active: false
        }
      }
    };
    tryCheckout = function(){
      if (state.form.agreed) {
        return state.triedCheckout = true;
      }
    };
    message = function(form, name){
      var field, val, ref$;
      for (field in fields) {
        if (fields.hasOwnProperty(field)) {
          val = (ref$ = form[field]) != null ? ref$.$error : void 8;
          if (val && isError(val)) {
            if (field === name) {
              return showErrorLogical(field, val);
            }
            return "";
          }
        }
      }
      return "";
    };
    placeholder = function(name){
      return fields[name].placeholder;
    };
    prefill(function(){
      var f, c;
      f = state.form;
      f.email = "test@debug.com";
      f.name = "Test User";
      f.phone = "+380665243646";
      f.address = "664 Cypress Lane, Campbell, CA, United States";
      f.notes = "Some test notes";
      c = state.form.creditCard;
      c.card = "5105 1051 0510 5100";
      c.address_zip = "12345";
      c.expDate = "05/17";
      c.cvv = "333";
      return state.form.agreed = true;
    });
    x$ = state;
    x$.handle = function(event){
      return safeApply(function(){
        var name, type, value, field;
        name = event.target.name;
        type = event.type;
        value = event.target.value;
        field = fields[name];
        switch (type) {
        case 'keyup':
          return typeof field.normalize == 'function' ? field.normalize(value) : void 8;
        case 'focus':
          field.state.active = true;
          return field.state.touched = true;
        case 'blur':
          return field.state.active = false;
        }
      });
    };
    x$.investigateDate = investigateDate;
    x$.getEventInstanceId = getEventInstanceId;
    x$.placeholder = placeholder;
    x$.closeError = closeError;
    x$.checkout = checkout;
    x$.validate = validate;
    x$.agree = agree;
    x$.fields = fields;
    x$.few = few;
    x$.disabledOrder = disabledOrder;
    x$.message = message;
    return state;
  };
});
