// Generated by LiveScript 1.5.0
(function(){
  angular.module('test').constant('enabledDebug', true).constant('ENV', {
    name: 'c9',
    imgBucket: '//dev-images.ablsolution.com/',
    widgetUrl: '//tour-widget-askucher.c9.io/',
    apiUrl: '//staging-api.adventurebucketlist.com/'
  });
}).call(this);
