// Generated by LiveScript 1.4.0
(function(){
  describe('calc', function(){
    beforeEach(module('test'));
    beforeEach(inject(function(_ablcalc_){
      return console.log(_ablcalc_);
    }));
    return it('test', function(done){});
  });
}).call(this);
